version: '3'
services:
  mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=tododb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vhaldemario
    volumes:
    - ./docker/mongodb:/data/db
    ports:
      - '27017:27017'
